package com.puntografico.puntografico.enums;

public enum MaterialASublimar {
    BIROME,
    TAZA_DE_POLIMERO,
    TAZA_DE_CERAMICA,
    TAZA_DE_CERAMICA_CON_DETALLE,
    TAZA_MAGICA,
    TELA,
    MATE_DE_POLIMERO,
    MATE_DE_CERAMICA,
    JARRO_DE_CAFE_DE_POLIMERO,
    LAPICERO_DE_POLIMERO,
    CINTA_FALLETINA,
    LLAVERO_CORTO_LANYARD,
    LLAVERO_LARGO_LANYARD,
    MOUSEPAD
}
